# ==============================================================================
# aerc keybindings
# Docs: https://aerc-mail.org/
# ==============================================================================

[messages]
q = :quit<Enter>
j = :next<Enter>
k = :prev<Enter>
g = :select 0<Enter>
G = :select -1<Enter>
<Enter> = :open<Enter>
d = :delete<Enter>
D = :delete!<Enter>
a = :archive flat<Enter>
C = :compose<Enter>
rr = :reply -a<Enter>
rq = :reply -aq<Enter>
Rr = :reply<Enter>
Rq = :reply -q<Enter>
/ = :search<space>
n = :next-result<Enter>
N = :prev-result<Enter>
<Escape> = :clear<Enter>
m = :move<space>

[view]
q = :close<Enter>
/ = :toggle-headers<Enter>
| = :pipe<space>
S = :save<space>
rr = :reply -a<Enter>
rq = :reply -aq<Enter>
Rr = :reply<Enter>
Rq = :reply -q<Enter>
d = :delete<Enter>
a = :archive flat<Enter>

[compose]
<C-k> = :prev-field<Enter>
<C-j> = :next-field<Enter>
<tab> = :next-field<Enter>
<C-p> = :prev-tab<Enter>
<C-n> = :next-tab<Enter>

[compose::editor]
<C-s> = :send<Enter>
<C-c> = :abort<Enter>
